[tool.poetry]
name = "labelimg"
version = "2.0.1.1"
description = "Graphical image annotation tool with bounding box support"
authors = ["TzuTa Lin <tzu.ta.lin@gmail.com>", "Qiang Wang <wangqiang2015@gmail.com>", "Junzhe Ye <yjz0918230128@foxmail.com>"]
license = "MIT"
#readme = "README.md"
homepage = "https://github.com/heartexlabs/labelImg"
repository = "https://github.com/heartexlabs/labelImg"
keywords = ["image-annotation", "bounding-box", "computer-vision", "labeling"]

[tool.poetry.scripts]
labelimg = "labelimg.labelImg:main"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
PySide6 = ">=6.6.0"
lxml = ">=5.1.0"
pillow = ">=10.2.0"
typing-extensions = ">=4.10.0"

[tool.poetry.dev-dependencies]
pytest = ">=8.0.0"
pytest-cov = ">=5.0.0"
black = ">=24.1.0"
isort = ">=5.13.2"
mypy = ">=1.8.0"
pre-commit = ">=3.6.0"
ruff = ">=0.3.0"

[tool.black]
line-length = 88
target-version = ['py310', 'py311', 'py312', 'py313']  # 添加3.13支持
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | build
  | dist
)/
'''

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "--cov=src/labelimg --cov-report=term-missing"

[build-system]
requires = ["poetry-core>=1.9.0"]  # 更新构建系统以支持3.13
build-backend = "poetry.core.masonry.api"
