name: Package
on: [ push, pull_request ]

jobs:
    package-macos:
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Python 3.12
                uses: actions/setup-python@v5
                with:
                    python-version: '3.12'
            -   name: Check resource files
                run: |
                    if [ ! -f "resources/strings/strings.properties" ]; then
                        echo "Error: resources/strings/strings.properties not found"
                        exit 1
                    fi
            -   name: Setup Python Environment
                run: |
                    python3 -m venv .venv
                    source .venv/bin/activate
                    pip3 install --upgrade pip
                    pip3 install pipenv
                    pipenv install pyside6==6.6.0 lxml
            -   name: Build LabelImg (PySide6)
                run: |
                    source .venv/bin/activate
                    pyside6-rcc resources.qrc -o libs/resources.py
                    rm -rf build dist
            -   name: Package LabelImg
                run: |
                    source .venv/bin/activate
                    pipenv run python setup.py py2app --includes=pyside6
                    open dist/labelImg.app
            -   name: Archive macOS app
                run: |
                    cd dist/
                    tar czf labelImg.tgz labelImg.app
            -   uses: actions/upload-artifact@v4
                with:
                    name: macOS artifact
                    path: dist/labelImg.tgz

    package-windows:
        runs-on: windows-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Python 3.12
                uses: actions/setup-python@v5
                with:
                    python-version: '3.12'
            -   name: Check resource files
                run: |
                    if (-not (Test-Path "resources/strings/strings.properties")) {
                        Write-Error "resources/strings/strings.properties not found"
                        exit 1
                    }
            -   name: Setup Python Environment
                run: |
                    python -m venv .venv
                    .venv\Scripts\activate
                    pip install --upgrade pip
                    pip install pyinstaller pyside6==6.6.0 lxml
            -   name: Build LabelImg (PySide6)
                run: |
                    .venv\Scripts\activate
                    pyside6-rcc resources.qrc -o libs/resources.py
            -   name: Package LabelImg
                run: |
                    .venv\Scripts\activate
                    pyinstaller --hidden-import=pyside6 --hidden-import=lxml -F -n "labelImg" -c labelImg.py -p ./libs -p ./
            -   uses: actions/upload-artifact@v4
                with:
                    name: Windows artifact
                    path: dist/labelImg.exe

    package-linux:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Python 3.12
                uses: actions/setup-python@v5

            -   name: Check resource files
                run: |
                    if [ ! -f "resources/strings/strings.properties" ]; then
                        echo "Error: resources/strings/strings.properties not found"
                        exit 1
                    fi
            -   name: Setup Python Environment
                run: |
                    sudo apt-get update && sudo apt-get install -y libxcb-xinerama0
                    python3 -m venv .venv
                    source .venv/bin/activate
                    pip3 install --upgrade pip
                    pip3 install pyinstaller pyside6==6.6.0 lxml
            -   name: Build LabelImg (PySide6)
                run: |
                    source .venv/bin/activate
                    pyside6-rcc resources.qrc -o libs/resources.py
            -   name: Package LabelImg
                run: |
                    source .venv/bin/activate
                    pyinstaller --hidden-import=pyside6 --hidden-import=lxml -F -n "labelImg" -c labelImg.py -p ./libs -p ./
            -   uses: actions/upload-artifact@v4
                with:
                    name: Linux artifact
                    path: dist/labelImg